export const people = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 2,
      id: 1911865,
      known_for: [
        {
          backdrop_path: "/t73x5Pb81mIGZR417aeGwbkR520.jpg",
          first_air_date: "2020-12-06",
          genre_ids: [18],
          id: 86430,
          media_type: "tv",
          name: "Your Honor",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Your Honor",
          overview:
            "New Orleans judge Michael Desiato is forced to confront his own deepest convictions when his son is involved in a hit and run that embroils an organized crime family.",
          poster_path: "/5NDs12paqvz4Jug3f13fC9XmSVN.jpg",
          vote_average: 8.2,
          vote_count: 1223,
        },
        {
          backdrop_path: "/sNLP0dLZcVBqYa3MchCXJqgDtFb.jpg",
          first_air_date: "2022-11-23",
          genre_ids: [10765, 9648, 35],
          id: 119051,
          media_type: "tv",
          name: "Wednesday",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Wednesday",
          overview:
            "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
          poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
          vote_average: 8.8,
          vote_count: 2618,
        },
        {
          backdrop_path: "/rX5hvSRB2k4YoIvRg6Zky52rWk0.jpg",
          first_air_date: "2016-10-02",
          genre_ids: [10765, 37],
          id: 63247,
          media_type: "tv",
          name: "Westworld",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Westworld",
          overview:
            "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
          poster_path: "/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
          vote_average: 8.1,
          vote_count: 4562,
        },
      ],
      known_for_department: "Acting",
      name: "Hunter Doohan",
      popularity: 427.07,
      profile_path: "/1rFocgirwZziZguJHYEGHqhVpdE.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 974169,
      known_for: [
        {
          backdrop_path: "/sNLP0dLZcVBqYa3MchCXJqgDtFb.jpg",
          first_air_date: "2022-11-23",
          genre_ids: [10765, 9648, 35],
          id: 119051,
          media_type: "tv",
          name: "Wednesday",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Wednesday",
          overview:
            "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
          poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
          vote_average: 8.8,
          vote_count: 2618,
        },
        {
          adult: false,
          backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
          genre_ids: [27, 9648, 53],
          id: 760104,
          media_type: "movie",
          original_language: "en",
          original_title: "X",
          overview:
            "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives. Hilarity ensues.",
          poster_path: "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
          release_date: "2022-03-17",
          title: "X",
          video: false,
          vote_average: 6.8,
          vote_count: 1351,
        },
        {
          adult: false,
          backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
          genre_ids: [27, 9648, 53],
          id: 646385,
          media_type: "movie",
          original_language: "en",
          original_title: "Scream",
          overview:
            "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
          poster_path: "/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
          release_date: "2022-01-12",
          title: "Scream",
          video: false,
          vote_average: 6.7,
          vote_count: 1900,
        },
      ],
      known_for_department: "Acting",
      name: "Jenna Ortega",
      popularity: 419.788,
      profile_path: "/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg",
    },
    {
      adult: false,
      gender: 1,
      id: 6886,
      known_for: [
        {
          adult: false,
          backdrop_path: "/g5hN9Kp4ShUcXmnjoaqg3LSWcHr.jpg",
          genre_ids: [14, 35, 10751],
          id: 8839,
          media_type: "movie",
          original_language: "en",
          original_title: "Casper",
          overview:
            "Casper is a kind young ghost who peacefully haunts a mansion in Maine. When specialist James Harvey arrives to communicate with Casper and his fellow spirits, he brings along his teenage daughter, Kat. Casper quickly falls in love with Kat, but their budding relationship is complicated not only by his transparent state, but also by his troublemaking apparition uncles and their mischievous antics.",
          poster_path: "/f8EuycdmuqMjlxFPm7awNJ9gLO8.jpg",
          release_date: "1995-05-26",
          title: "Casper",
          video: false,
          vote_average: 6.3,
          vote_count: 4013,
        },
        {
          adult: false,
          backdrop_path: "/nVi8CINgtMbWmCQ0XxXgW2H1ZTW.jpg",
          genre_ids: [18, 14, 53, 9648, 27],
          id: 2668,
          media_type: "movie",
          original_language: "en",
          original_title: "Sleepy Hollow",
          overview:
            "New York detective Ichabod Crane is sent to Sleepy Hollow to investigate a series of mysterious deaths in which the victims are found beheaded. Locals believe the culprit to be none other than the legendary Headless Horseman.",
          poster_path: "/660DFxWpSfZ1d1PruZ6Nd9vKXNE.jpg",
          release_date: "1999-11-19",
          title: "Sleepy Hollow",
          video: false,
          vote_average: 7.2,
          vote_count: 5790,
        },
        {
          adult: false,
          backdrop_path: "/kbD1di34NzIJAhorYxUob1PR7cR.jpg",
          genre_ids: [14, 35, 10749],
          id: 7985,
          media_type: "movie",
          original_language: "en",
          original_title: "Penelope",
          overview:
            "Forlorn heiress Penelope Wilhern is cursed, and the only way out is to fall in love with someone of suitable stock. But how can she find her soul mate when she's sequestered inside her family's estate with only her parents to keep her company. This untraditional fairy tale about a girl who bucks convention to create her own happy ending.",
          poster_path: "/eZDxWKfCYxUE53Ke02AE5yjU1o0.jpg",
          release_date: "2006-03-01",
          title: "Penelope",
          video: false,
          vote_average: 6.7,
          vote_count: 1253,
        },
      ],
      known_for_department: "Acting",
      name: "Christina Ricci",
      popularity: 206.763,
      profile_path: "/m2cY5Er1loPgHkZYdFMEz6YeiwG.jpg",
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
