const people = [
  {
    adult: false,
    gender: 2,
    id: 1911865,
    known_for: [
      {
        backdrop_path: "/t73x5Pb81mIGZR417aeGwbkR520.jpg",
        first_air_date: "2020-12-06",
        genre_ids: [18],
        id: 86430,
        media_type: "tv",
        name: "Your Honor",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Your Honor",
        overview:
          "New Orleans judge Michael Desiato is forced to confront his own deepest convictions when his son is involved in a hit and run that embroils an organized crime family.",
        poster_path: "/5NDs12paqvz4Jug3f13fC9XmSVN.jpg",
        vote_average: 8.2,
        vote_count: 1223,
      },
      {
        backdrop_path: "/sNLP0dLZcVBqYa3MchCXJqgDtFb.jpg",
        first_air_date: "2022-11-23",
        genre_ids: [10765, 9648, 35],
        id: 119051,
        media_type: "tv",
        name: "Wednesday",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Wednesday",
        overview:
          "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
        poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        vote_average: 8.8,
        vote_count: 2618,
      },
      {
        backdrop_path: "/rX5hvSRB2k4YoIvRg6Zky52rWk0.jpg",
        first_air_date: "2016-10-02",
        genre_ids: [10765, 37],
        id: 63247,
        media_type: "tv",
        name: "Westworld",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Westworld",
        overview:
          "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
        poster_path: "/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
        vote_average: 8.1,
        vote_count: 4562,
      },
    ],
    known_for_department: "Acting",
    name: "Hunter Doohan",
    popularity: 427.07,
    profile_path: "/1rFocgirwZziZguJHYEGHqhVpdE.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 974169,
    known_for: [
      {
        adult: false,
        backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
        genre_ids: [27, 9648, 53],
        id: 760104,
        media_type: "movie",
        original_language: "en",
        original_title: "X",
        overview:
          "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives. Hilarity ensues.",
        poster_path: "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
        release_date: "2022-03-17",
        title: "X",
        video: false,
        vote_average: 6.8,
        vote_count: 1351,
      },
      {
        adult: false,
        backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
        genre_ids: [27, 9648, 53],
        id: 646385,
        media_type: "movie",
        original_language: "en",
        original_title: "Scream",
        overview:
          "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
        poster_path: "/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
        release_date: "2022-01-12",
        title: "Scream",
        video: false,
        vote_average: 6.7,
        vote_count: 1900,
      },
    ],
    known_for_department: "Acting",
    name: "Jenna Ortega",
    popularity: 419.788,
    profile_path: "/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 6886,
    known_for: [
      {
        adult: false,
        backdrop_path: "/g5hN9Kp4ShUcXmnjoaqg3LSWcHr.jpg",
        genre_ids: [14, 35, 10751],
        id: 8839,
        media_type: "movie",
        original_language: "en",
        original_title: "Casper",
        overview:
          "Casper is a kind young ghost who peacefully haunts a mansion in Maine. When specialist James Harvey arrives to communicate with Casper and his fellow spirits, he brings along his teenage daughter, Kat. Casper quickly falls in love with Kat, but their budding relationship is complicated not only by his transparent state, but also by his troublemaking apparition uncles and their mischievous antics.",
        poster_path: "/f8EuycdmuqMjlxFPm7awNJ9gLO8.jpg",
        release_date: "1995-05-26",
        title: "Casper",
        video: false,
        vote_average: 6.3,
        vote_count: 4013,
      },
      {
        adult: false,
        backdrop_path: "/nVi8CINgtMbWmCQ0XxXgW2H1ZTW.jpg",
        genre_ids: [18, 14, 53, 9648, 27],
        id: 2668,
        media_type: "movie",
        original_language: "en",
        original_title: "Sleepy Hollow",
        overview:
          "New York detective Ichabod Crane is sent to Sleepy Hollow to investigate a series of mysterious deaths in which the victims are found beheaded. Locals believe the culprit to be none other than the legendary Headless Horseman.",
        poster_path: "/660DFxWpSfZ1d1PruZ6Nd9vKXNE.jpg",
        release_date: "1999-11-19",
        title: "Sleepy Hollow",
        video: false,
        vote_average: 7.2,
        vote_count: 5790,
      },
      {
        adult: false,
        backdrop_path: "/kbD1di34NzIJAhorYxUob1PR7cR.jpg",
        genre_ids: [14, 35, 10749],
        id: 7985,
        media_type: "movie",
        original_language: "en",
        original_title: "Penelope",
        overview:
          "Forlorn heiress Penelope Wilhern is cursed, and the only way out is to fall in love with someone of suitable stock. But how can she find her soul mate when she's sequestered inside her family's estate with only her parents to keep her company. This untraditional fairy tale about a girl who bucks convention to create her own happy ending.",
        poster_path: "/eZDxWKfCYxUE53Ke02AE5yjU1o0.jpg",
        release_date: "2006-03-01",
        title: "Penelope",
        video: false,
        vote_average: 6.7,
        vote_count: 1253,
      },
    ],
    known_for_department: "Acting",
    name: "Christina Ricci",
    popularity: 206.763,
    profile_path: "/m2cY5Er1loPgHkZYdFMEz6YeiwG.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 2604515,
    known_for: [
      {
        adult: false,
        backdrop_path: "/fvUmnxS9xaUUl0eWygvcA1hPdTV.jpg",
        genre_ids: [80, 53, 10770],
        id: 801335,
        media_type: "movie",
        original_language: "en",
        original_title: "Girl in the Basement",
        overview:
          "Sara is a teen girl who is looking forward to her 18th birthday to move away from her controlling father Don. But before she could even blow out the candles, Don imprisons her in the basement of their home.",
        poster_path: "/qmddUxRwbsxHa7oEXm4PWh1KZe8.jpg",
        release_date: "2021-02-27",
        title: "Girl in the Basement",
        video: false,
        vote_average: 7.9,
        vote_count: 443,
      },
      {
        adult: false,
        backdrop_path: "/x6R3WtdEUPbAKKi75haYvF8JbQG.jpg",
        genre_ids: [10749, 10770],
        id: 744938,
        media_type: "movie",
        original_language: "en",
        original_title: "A Taste of Christmas",
        overview:
          "When Natalie (Anni Krueger) learns her cousin Francesca (Nia Vardalos) must cancel the Christmas Eve opening of her new Italian restaurant, Natalie’s heart goes out to all of the guests who were planning on attending. Since no one should be alone on Christmas, Natalie decides to make the opening happen any way she can. However, the attractive but pessimistic Chef Stefano (Gilles Marini) believes it’s impossible – there are only three days until Christmas! But Natalie insists that problems are just opportunities in disguise and soon she convinces Stefano that they can do it. At first, these opposites do not attract, but feelings begin to change when they find themselves working side-by-side. With Stefano’s help Natalie learns that cooking, like Christmas, isn’t about perfection…it’s about sharing it with the ones you love.",
        poster_path: "/3LlpRHEgNa4VzuOjkKU7ZRQ40NG.jpg",
        release_date: "2020-11-20",
        title: "A Taste of Christmas",
        video: false,
        vote_average: 5.9,
        vote_count: 9,
      },
    ],
    known_for_department: "Acting",
    name: "Emma Myers",
    popularity: 199.021,
    profile_path: "/e5eTDKstLsUKKfmwgiJsDakcvly.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1907997,
    known_for: [
      {
        adult: false,
        backdrop_path: "/35V5CNHsJAcu1k5YtRCasn3sUtR.jpg",
        genre_ids: [10749],
        id: 685090,
        media_type: "movie",
        original_language: "ko",
        original_title: "여선생 3",
        overview:
          "Ji-eun decides to become a tutor for Sang-woo's son, Sang-woo, in order to make sure he has a rich boyfriend.  When tutoring begins, Sang-woo, who was kicked by her older sister Hye-ran, is attracted to Ji-eun, who kindly teaches herself.  One day, Sang-woo witnesses the love affair of his father and Ji-eun, and falls into a sense of loss.  Meanwhile, Ji-eun overhears Ji-eun's conversations with a friend, and notices that Ji-eun's only goal is to meet her. In the end, Ji-eun notifies Ji-eun.  Ji-eun arrives to attend the last class, and because of her appointment with Sang-woo, she eventually gives up her body.",
        poster_path: "/ltT8NysDFAwRNyysIubYRMnUqaG.jpg",
        release_date: "2020-03-20",
        title: "Schoolmistress 3",
        video: false,
        vote_average: 6.4,
        vote_count: 5,
      },
      {
        adult: false,
        backdrop_path: "/lIiqPqifLnUSMRH5xJrPlASW64H.jpg",
        genre_ids: [18, 10749],
        id: 652836,
        media_type: "movie",
        original_language: "ko",
        original_title: "채팅앱-누나의맛",
        overview:
          "Ye-sung and Seok-hun are senior juniors who have nothing to do. One day, Ye-seong, who found an app that relieves women's discomfort, met Seo Hye-ji through a chat app and had a chance to see her. I ask you… Yeseong tells Seokhoon about the chat app as well as signing up for Seokhoon's housework. .Seokhundo app will meet with women to have fun sex. After that, Seokhoon meets women through the chat app while working hard. As more and more Seokhoon than Yeseong is becoming more popular with women in the chat app, women are looking for Seokhun rather than Yeseong, and Yeseong is surprised by the popularity of Seokhun and is driven out of the house.",
        poster_path: "/qLXTb41e9CNzXhvOkKArdWU5Jno.jpg",
        release_date: "2019-11-22",
        title: "Chatting App Sister Taste",
        video: false,
        vote_average: 5.3,
        vote_count: 3,
      },
      {
        adult: false,
        backdrop_path: "/2p6LxBSNPWn3bTcmTDs9XDmEQB4.jpg",
        genre_ids: [18, 80, 10749],
        id: 663172,
        media_type: "movie",
        original_language: "ko",
        original_title: "불량탐정 : 미씽",
        overview:
          "Mi-ri's friends, who work in a private detective office, leave on a trip to South East Asia. But suddenly, Mi-ri loses contact with her friends, and their whereabouts are unknown. Mi-ri is sure they have been abducted and asks a detective for help...\r The detective looks into the case, but where will he find Mi-ri's friends?",
        poster_path: "/aAhCvyJZq5BPWTUPO74N9CouFvy.jpg",
        release_date: "2019-12-25",
        title: "Bad Detective: Missing",
        video: false,
        vote_average: 3.2,
        vote_count: 3,
      },
    ],
    known_for_department: "Acting",
    name: "Min Do-yoon",
    popularity: 176.242,
    profile_path: "/bHHn3krbHyxQIWb4JbHkPlV6Uu1.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1011904,
    known_for: [
      {
        backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
        first_air_date: "2011-04-17",
        genre_ids: [10765, 18, 10759],
        id: 1399,
        media_type: "tv",
        name: "Game of Thrones",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Game of Thrones",
        overview:
          "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
        vote_average: 8.4,
        vote_count: 19943,
      },
      {
        adult: false,
        backdrop_path: "/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg",
        genre_ids: [12, 28, 878, 14],
        id: 140607,
        media_type: "movie",
        original_language: "en",
        original_title: "Star Wars: The Force Awakens",
        overview:
          "Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.",
        poster_path: "/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
        release_date: "2015-12-15",
        title: "Star Wars: The Force Awakens",
        video: false,
        vote_average: 7.3,
        vote_count: 17521,
      },
      {
        adult: false,
        backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
        genre_ids: [12, 28, 878],
        id: 181808,
        media_type: "movie",
        original_language: "en",
        original_title: "Star Wars: The Last Jedi",
        overview:
          "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
        poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
        release_date: "2017-12-13",
        title: "Star Wars: The Last Jedi",
        video: false,
        vote_average: 6.9,
        vote_count: 13517,
      },
    ],
    known_for_department: "Acting",
    name: "Gwendoline Christie",
    popularity: 168.623,
    profile_path: "/kmlv5i02n3zKryBr2W3kSeWVKTD.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 6614,
    known_for: [
      {
        adult: false,
        backdrop_path: "/bpV8wn48s82au37QyUJ51S7X2Vf.jpg",
        genre_ids: [18],
        id: 489,
        media_type: "movie",
        original_language: "en",
        original_title: "Good Will Hunting",
        overview:
          "Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire.",
        poster_path: "/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg",
        release_date: "1997-12-05",
        title: "Good Will Hunting",
        video: false,
        vote_average: 8.1,
        vote_count: 10144,
      },
      {
        adult: false,
        backdrop_path: "/uQ1NLTPJ7g1Skg4eD9vHh3RTRlm.jpg",
        genre_ids: [53, 878, 28],
        id: 2787,
        media_type: "movie",
        original_language: "en",
        original_title: "Pitch Black",
        overview:
          "When their ship crash-lands on a remote planet, the marooned passengers soon learn that escaped convict Riddick isn't the only thing they have to fear. Deadly creatures lurk in the shadows, waiting to attack in the dark, and the planet is rapidly plunging into the utter blackness of a total eclipse. With the body count rising, the doomed survivors are forced to turn to Riddick with his eerie eyes to guide them through the darkness to safety. With time running out, there's only one rule: Stay in the light.",
        poster_path: "/3AnlxZ5CZnhKKzjgFyY6EHxmOyl.jpg",
        release_date: "2000-02-18",
        title: "Pitch Black",
        video: false,
        vote_average: 6.8,
        vote_count: 3817,
      },
      {
        adult: false,
        backdrop_path: "/z3ioibdjWZOYeXjoiabFOFOfPI3.jpg",
        genre_ids: [28, 80, 53],
        id: 584,
        media_type: "movie",
        original_language: "en",
        original_title: "2 Fast 2 Furious",
        overview:
          "It's a major double-cross when former police officer Brian O'Conner teams up with his ex-con buddy Roman Pearce to transport a shipment of \"dirty\" money for shady Miami-based import-export dealer Carter Verone. But the guys are actually working with undercover agent Monica Fuentes to bring Verone down.",
        poster_path: "/qC167IbZpSrwX7wWgg3BeDQbTDr.jpg",
        release_date: "2003-06-05",
        title: "2 Fast 2 Furious",
        video: false,
        vote_average: 6.5,
        vote_count: 6241,
      },
    ],
    known_for_department: "Acting",
    name: "Cole Hauser",
    popularity: 156.184,
    profile_path: "/kJyUtNZREd7mes21OrWiCtOugPL.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1477961,
    known_for: [
      {
        backdrop_path: "/18inwHlpKnK9mt02wFBJoIVKXI.jpg",
        first_air_date: "2017-10-02",
        genre_ids: [10765, 10759, 18],
        id: 69629,
        media_type: "tv",
        name: "The Gifted",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Gifted",
        overview:
          "A suburban couple's ordinary lives are rocked by the sudden discovery that their children possess mutant powers. Forced to go on the run from a hostile government, the family joins up with an underground network of mutants and must fight to survive.",
        poster_path: "/nshCqszjTNuqhrB53vrSqWO18sE.jpg",
        vote_average: 7.7,
        vote_count: 1288,
      },
      {
        adult: false,
        backdrop_path: "/8b9mOlxer8DVw4k368IXNG5HPBI.jpg",
        genre_ids: [12, 35, 14, 10751],
        id: 181533,
        media_type: "movie",
        original_language: "en",
        original_title: "Night at the Museum: Secret of the Tomb",
        overview:
          "When the magic powers of The Tablet of Ahkmenrah begin to die out, Larry Daley spans the globe, uniting favorite and new characters while embarking on an epic quest to save the magic before it is gone forever.",
        poster_path: "/xwgy305K6qDs3D20xUO4OZu1HPY.jpg",
        release_date: "2014-12-17",
        title: "Night at the Museum: Secret of the Tomb",
        video: false,
        vote_average: 6.2,
        vote_count: 5202,
      },
    ],
    known_for_department: "Acting",
    name: "Percy Hynes White",
    popularity: 148.31,
    profile_path: "/hOS1vYWvTTXugOWhAGXoBH7dGHN.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 225810,
    known_for: [
      {
        adult: false,
        backdrop_path: "/7Gu4Qw1Xwku1hsdg0dD4weiLSA9.jpg",
        genre_ids: [27],
        id: 56937,
        media_type: "movie",
        original_language: "no",
        original_title: "Fritt vilt III",
        overview:
          "In 1988, a group of teenagers go to visit an abandoned hotel, only to find themselves hunted by a psychotic killer through the Norwegian woods.",
        poster_path: "/b1GYIevdcbdCN8OCMEjMmGYd1D4.jpg",
        release_date: "2010-10-15",
        title: "Cold Prey III",
        video: false,
        vote_average: 5.9,
        vote_count: 121,
      },
      {
        adult: false,
        backdrop_path: "/hNpExSqRqOzrQZ0U63xkqubt4eO.jpg",
        genre_ids: [35, 10749],
        id: 38398,
        media_type: "movie",
        original_language: "no",
        original_title: "Bare Bea",
        overview:
          "16 year-old Bea is in her first year at upper secondary school in Oslo. Active on the school magazine, she falls in love with Daniel, the smartest and most gifted student in the top year, who returns her feelings. There is just one drawback, namely her friend' idea of virginity and first love...",
        poster_path: "/8ejChMekZyl3lAzzvGlo0OCDQLg.jpg",
        release_date: "2004-01-23",
        title: "Just Bea",
        video: false,
        vote_average: 5.8,
        vote_count: 16,
      },
      {
        adult: false,
        backdrop_path: "/zmM5wIYBaOp0aKM4EoLbrvMuctF.jpg",
        genre_ids: [35],
        id: 247290,
        media_type: "movie",
        original_language: "no",
        original_title: "Kill Buljo 2",
        overview:
          "Jompa Tormann is back, and everything is better, except the humor, which is even worse than in the first movie of vengeance.",
        poster_path: "/v0VP7zEp3qlLJ9wK48byEBzYBQv.jpg",
        release_date: "2013-12-20",
        title: "Kill Buljo 2",
        video: false,
        vote_average: 5.1,
        vote_count: 12,
      },
    ],
    known_for_department: "Acting",
    name: "Kim S. Falck-Jørgensen",
    popularity: 146.695,
    profile_path: "/pMwD3F5ANWQNF9UU3KivLt2EgFa.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 2189049,
    known_for: [
      {
        adult: false,
        backdrop_path: "/as4jvr6PF7Wfs0RyUl5bOJcB3yt.jpg",
        genre_ids: [18, 35],
        id: 626735,
        media_type: "movie",
        original_language: "en",
        original_title: "Dog",
        overview:
          "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
        poster_path: "/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg",
        release_date: "2022-02-17",
        title: "Dog",
        video: false,
        vote_average: 7.4,
        vote_count: 1037,
      },
      {
        adult: false,
        backdrop_path: "/rAQLRypzIl0IiXKvIUFLt3UhHuA.jpg",
        genre_ids: [35, 18, 10749],
        id: 637053,
        media_type: "movie",
        original_language: "en",
        original_title: "Shithouse",
        overview:
          'Lonely college freshman Alex has closed himself off from his peers, who all appear to have this whole "college thing" figured out. But everything changes one night when Alex takes a leap and attends a party at Shithouse - a legendary party fraternity - where he forges a strong connection with Maggie.',
        poster_path: "/u9Yv1kISlhOszo7NJOpGmSQLDG1.jpg",
        release_date: "2020-10-16",
        title: "Shithouse",
        video: false,
        vote_average: 7.1,
        vote_count: 111,
      },
    ],
    known_for_department: "Acting",
    name: "Joy Sunday",
    popularity: 138.788,
    profile_path: "/fTajkqbVGMU4O2LMteuYlffhfJI.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1813898,
    known_for: [
      {
        adult: false,
        backdrop_path: "/3sF6AibdbTTkswfSRxXEGCt5w6s.jpg",
        genre_ids: [28, 12, 14],
        id: 847,
        media_type: "movie",
        original_language: "en",
        original_title: "Willow",
        overview:
          "The evil Queen Bavmorda hunts the newborn princess Elora Danan, a child prophesied to bring about her downfall. When the royal infant is found by Willow, a timid farmer and aspiring sorcerer, he's entrusted with delivering her from evil.",
        poster_path: "/d9xEILdvVRX8ZgFwPDbco6kKSaS.jpg",
        release_date: "1988-05-20",
        title: "Willow",
        video: false,
        vote_average: 7,
        vote_count: 1540,
      },
      {
        adult: false,
        backdrop_path: "/3mnFUOqzmUb71lSwR2p34nISDl4.jpg",
        genre_ids: [53],
        id: 361149,
        media_type: "movie",
        original_language: "en",
        original_title: "Road to Nowhere",
        overview:
          "An escaped convict goes on the run with his younger, mentally fragile sister of whom is he insanely possessive. Cornered by roadblocks, they take up shelter in the isolated home of a young couple on their honeymoon.",
        release_date: "1993-07-04",
        title: "Road to Nowhere",
        video: false,
        vote_average: 6.5,
        vote_count: 1,
      },
    ],
    known_for_department: "Acting",
    name: "Julie Peters",
    popularity: 137.304,
    profile_path: null,
  },
  {
    adult: false,
    gender: 1,
    id: 1394758,
    known_for: [
      {
        adult: false,
        backdrop_path: "/53BC9F2tpZnsGno2cLhzvGprDYS.jpg",
        genre_ids: [14, 28, 12],
        id: 736526,
        media_type: "movie",
        original_language: "no",
        original_title: "Troll",
        overview:
          "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
        poster_path: "/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
        release_date: "2022-12-01",
        title: "Troll",
        video: false,
        vote_average: 6.8,
        vote_count: 474,
      },
      {
        backdrop_path: "/xgNniC0uFUHJUM9zjThda9fZQGe.jpg",
        first_air_date: "2021-09-26",
        genre_ids: [18, 80],
        id: 130219,
        media_type: "tv",
        name: "Furia",
        origin_country: ["NO"],
        original_language: "no",
        original_name: "Furia",
        overview:
          "Policeman Asgeir moves to an idyllic town in the west part of Norway. After a local conflict, he meets a mysterious woman named Ragna, and soon they are both trapped in a network of right-wing radical forces that threaten Europe.",
        poster_path: "/kmApIHsFUTqcEdF8QpLhdwTlhSl.jpg",
        vote_average: 6.6,
        vote_count: 78,
      },
      {
        adult: false,
        backdrop_path: "/swcQcBI1ZBBvYvbq7wf4QZ0knM0.jpg",
        genre_ids: [18],
        id: 308403,
        media_type: "movie",
        original_language: "no",
        original_title: "De nærmeste",
        overview:
          "When Charlotte, 27, meets her brother Henrik, 35, for the first time as an adult, it becomes an encounter without boundaries, between two people who don't know what a normal family is. How does sibling love manifest itself if you have never experienced it before? Homesick is an unusual family drama about seeking a family, and breaking every rule to be one.",
        poster_path: "/tumYr6OiW5BGTIqD4w1az2JhXiO.jpg",
        release_date: "2015-03-27",
        title: "Homesick",
        video: false,
        vote_average: 4.9,
        vote_count: 29,
      },
    ],
    known_for_department: "Acting",
    name: "Ine Marie Wilmann",
    popularity: 132.548,
    profile_path: "/bu9JEeHHOl9kHGXzxVsNf8B4FDm.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 7673,
    known_for: [
      {
        adult: false,
        backdrop_path: "/fgkgab4Rel0nOI3B3scHeNB4Mn6.jpg",
        genre_ids: [28, 53],
        id: 1573,
        media_type: "movie",
        original_language: "en",
        original_title: "Die Hard 2",
        overview:
          "Off-duty cop John McClane is gripped with a feeling of déjà vu when, on a snowy Christmas Eve in the nation’s capital, terrorists seize a major international airport, holding thousands of holiday travelers hostage. Renegade military commandos led by a murderous rogue officer plot to rescue a drug lord from justice and are prepared for every contingency except one: McClane’s smart-mouthed heroics.",
        poster_path: "/56QECFJxueUVJAppVxwEE9ZDYrn.jpg",
        release_date: "1990-07-02",
        title: "Die Hard 2",
        video: false,
        vote_average: 6.9,
        vote_count: 4900,
      },
      {
        adult: false,
        backdrop_path: "/oIwfoUFfWfESn0Y8u8jv9lc8li1.jpg",
        genre_ids: [28, 53],
        id: 562,
        media_type: "movie",
        original_language: "en",
        original_title: "Die Hard",
        overview:
          "NYPD cop John McClane's plan to reconcile with his estranged wife is thrown for a serious loop when, minutes after he arrives at her office, the entire building is overtaken by a group of terrorists. With little help from the LAPD, wisecracking McClane sets out to single-handedly rescue the hostages and bring the bad guys down.",
        poster_path: "/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg",
        release_date: "1988-07-15",
        title: "Die Hard",
        video: false,
        vote_average: 7.8,
        vote_count: 9511,
      },
      {
        adult: false,
        backdrop_path: "/c1iknOAPmCbEz14axls06Hs1MoJ.jpg",
        genre_ids: [53, 80, 9648],
        id: 11092,
        media_type: "movie",
        original_language: "en",
        original_title: "Presumed Innocent",
        overview:
          "Rusty Sabich is a deputy prosecutor engaged in an obsessive affair with a coworker who is murdered. Soon after, he's accused of the crime. And his fight to clear his name becomes a whirlpool of lies and hidden passions.",
        poster_path: "/jSPWptOsqU1nxXQe6muSPB0kD3c.jpg",
        release_date: "1990-07-26",
        title: "Presumed Innocent",
        video: false,
        vote_average: 6.8,
        vote_count: 533,
      },
    ],
    known_for_department: "Acting",
    name: "Bonnie Bedelia",
    popularity: 129.878,
    profile_path: "/2dCd7HGOfmn4x7v97EcNIwy12io.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 125025,
    known_for: [
      {
        adult: false,
        backdrop_path: "/aqrDUkuzksLhOD8pbyBXLO0dz5t.jpg",
        genre_ids: [10749, 35],
        id: 454983,
        media_type: "movie",
        original_language: "en",
        original_title: "The Kissing Booth",
        overview:
          "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
        poster_path: "/7Dktk2ST6aL8h9Oe5rpk903VLhx.jpg",
        release_date: "2018-05-11",
        title: "The Kissing Booth",
        video: false,
        vote_average: 7.3,
        vote_count: 6692,
      },
      {
        adult: false,
        backdrop_path: "/bXdCpL1A1mW2sEBiTmYYFnb10XN.jpg",
        genre_ids: [35, 10749],
        id: 583083,
        media_type: "movie",
        original_language: "en",
        original_title: "The Kissing Booth 2",
        overview:
          "With college decisions looming, Elle juggles her long-distance romance with Noah, changing relationship with bestie Lee and feelings for a new classmate.",
        poster_path: "/mb7wQv0adK3kjOUr9n93mANHhPJ.jpg",
        release_date: "2020-07-24",
        title: "The Kissing Booth 2",
        video: false,
        vote_average: 7.8,
        vote_count: 4634,
      },
      {
        backdrop_path: "/1yhQGQH7pfKdIY2xJSYNdp8ReD6.jpg",
        first_air_date: "2019-03-20",
        genre_ids: [18, 80],
        id: 82883,
        media_type: "tv",
        name: "The Act",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Act",
        overview:
          "A seasonal anthology series that tells startling, stranger-than-fiction true crime stories with the first season following Gypsy Blanchard, a girl trying to escape the toxic relationship she has with her overprotective mother.",
        poster_path: "/vb1sQLC2MqfCPOFqHd8SyVsyDVB.jpg",
        vote_average: 7.6,
        vote_count: 4807,
      },
    ],
    known_for_department: "Acting",
    name: "Joey King",
    popularity: 126.187,
    profile_path: "/kL0lWLJA6lbvmPM3YL0ISE6rVr6.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1136406,
    known_for: [
      {
        adult: false,
        backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
        genre_ids: [28, 12, 878, 18],
        id: 315635,
        media_type: "movie",
        original_language: "en",
        original_title: "Spider-Man: Homecoming",
        overview:
          "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
        poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
        release_date: "2017-07-05",
        title: "Spider-Man: Homecoming",
        video: false,
        vote_average: 7.4,
        vote_count: 19357,
      },
      {
        adult: false,
        backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
        genre_ids: [28, 12, 878],
        id: 634649,
        media_type: "movie",
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        poster_path: "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
        release_date: "2021-12-15",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 8,
        vote_count: 16024,
      },
      {
        adult: false,
        backdrop_path: "/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg",
        genre_ids: [28, 12, 878],
        id: 429617,
        media_type: "movie",
        original_language: "en",
        original_title: "Spider-Man: Far from Home",
        overview:
          "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
        poster_path: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
        release_date: "2019-06-28",
        title: "Spider-Man: Far from Home",
        video: false,
        vote_average: 7.5,
        vote_count: 13391,
      },
    ],
    known_for_department: "Acting",
    name: "Tom Holland",
    popularity: 102.892,
    profile_path: "/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 17521,
    known_for: [
      {
        adult: false,
        backdrop_path: "/mG8PDdaCANAVQMrjTKc69Z7NjF3.jpg",
        genre_ids: [18],
        id: 87502,
        media_type: "movie",
        original_language: "en",
        original_title: "Flight",
        overview:
          "Commercial airline pilot Whip Whitaker has a problem with drugs and alcohol, though so far he's managed to complete his flights safely. His luck runs out when a disastrous mechanical malfunction sends his plane hurtling toward the ground. Whip pulls off a miraculous crash-landing that results in only six lives lost. Shaken to the core, Whip vows to get sober -- but when the crash investigation exposes his addiction, he finds himself in an even worse situation.",
        poster_path: "/1AjXgBM2lkpG3FLQO0f6AK3Bi1e.jpg",
        release_date: "2012-11-02",
        title: "Flight",
        video: false,
        vote_average: 6.8,
        vote_count: 5277,
      },
      {
        adult: false,
        backdrop_path: "/veXdzn7LL0bFIDGmE7tTkvRg0qV.jpg",
        genre_ids: [28, 12, 80, 9648],
        id: 10528,
        media_type: "movie",
        original_language: "en",
        original_title: "Sherlock Holmes",
        overview:
          "Eccentric consulting detective Sherlock Holmes and Doctor John Watson battle to bring down a new nemesis and unravel a deadly plot that could destroy England.",
        poster_path: "/momkKuWburNTqKBF6ez7rvhYVhE.jpg",
        release_date: "2009-12-23",
        title: "Sherlock Holmes",
        video: false,
        vote_average: 7.2,
        vote_count: 12622,
      },
      {
        adult: false,
        backdrop_path: "/s9v1QZMVhwShQ7415jPhtfqzyjG.jpg",
        genre_ids: [27, 53],
        id: 13510,
        media_type: "movie",
        original_language: "en",
        original_title: "Eden Lake",
        overview:
          "Eden Lake is a relentlessly tense and immaculately paced horror-thriller about modern youth gone wild. When a young couple goes to a remote wooded lake for a romantic getaway, their quiet weekend is shattered by an aggressive group of local kids. Rowdiness quickly turns to rage as the teens terrorize the couple in unimaginable ways, and a weekend outing becomes a bloody battle for survival.",
        poster_path: "/lotoZbXMJxyoxx4AS48bNMp5BjS.jpg",
        release_date: "2008-09-12",
        title: "Eden Lake",
        video: false,
        vote_average: 6.8,
        vote_count: 1417,
      },
    ],
    known_for_department: "Acting",
    name: "Kelly Reilly",
    popularity: 100.79,
    profile_path: "/gof8bWW9E7MH30GpvA97PwGiIuu.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 6161,
    known_for: [
      {
        adult: false,
        backdrop_path: "/vVBcIN68kFq681b4lObiNJhEVro.jpg",
        genre_ids: [18, 10749],
        id: 453,
        media_type: "movie",
        original_language: "en",
        original_title: "A Beautiful Mind",
        overview:
          "John Nash is a brilliant but asocial mathematician fighting schizophrenia. After he accepts secret work in cryptography, his life takes a turn for the nightmarish.",
        poster_path: "/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
        release_date: "2001-12-11",
        title: "A Beautiful Mind",
        video: false,
        vote_average: 7.9,
        vote_count: 8899,
      },
      {
        adult: false,
        backdrop_path: "/7jR6xSOqnWCrm3OGhm06Y8jGCYS.jpg",
        genre_ids: [80, 18],
        id: 641,
        media_type: "movie",
        original_language: "en",
        original_title: "Requiem for a Dream",
        overview:
          "The hopes and dreams of four ambitious people are shattered when their drug addictions begin spiraling out of control. A look into addiction and how it overcomes the mind and body.",
        poster_path: "/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
        release_date: "2000-10-06",
        title: "Requiem for a Dream",
        video: false,
        vote_average: 8,
        vote_count: 8502,
      },
      {
        adult: false,
        backdrop_path: "/5z75Q6nqgwgYfpMB9fVHQcw9gMz.jpg",
        genre_ids: [18, 12],
        id: 86834,
        media_type: "movie",
        original_language: "en",
        original_title: "Noah",
        overview:
          "A man who suffers visions of an apocalyptic deluge takes measures to protect his family from the coming flood.",
        poster_path: "/trtD17IqSWV9Nbn4OILztc9GuCX.jpg",
        release_date: "2014-03-07",
        title: "Noah",
        video: false,
        vote_average: 5.6,
        vote_count: 5569,
      },
    ],
    known_for_department: "Acting",
    name: "Jennifer Connelly",
    popularity: 100.668,
    profile_path: "/opBts8lC3ZhK4BQwl8ztczehsFQ.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 56734,
    known_for: [
      {
        adult: false,
        backdrop_path: "/hqrwXs3KqPuU5rWoconbmQUn6rh.jpg",
        genre_ids: [878, 12, 28],
        id: 299687,
        media_type: "movie",
        original_language: "en",
        original_title: "The 5th Wave",
        overview:
          "16-year-old Cassie Sullivan tries to survive in a world devastated by the waves of an alien invasion that has already decimated the population and knocked mankind back to the Stone Age.",
        poster_path: "/nK5BR028wjh3b8HrZb9LADhDDiA.jpg",
        release_date: "2016-01-14",
        title: "The 5th Wave",
        video: false,
        vote_average: 5.9,
        vote_count: 5250,
      },
      {
        adult: false,
        backdrop_path: "/P4bGyJQF0shAcRku3I2perNUQR.jpg",
        genre_ids: [28, 80],
        id: 23483,
        media_type: "movie",
        original_language: "en",
        original_title: "Kick-Ass",
        overview:
          "Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.",
        poster_path: "/8citjdBmjddZjlPsAHEyCKwGVvD.jpg",
        release_date: "2010-03-22",
        title: "Kick-Ass",
        video: false,
        vote_average: 7.1,
        vote_count: 10446,
      },
      {
        adult: false,
        backdrop_path: "/8DkbabWAQkZpwn923e4DpjZmOuo.jpg",
        genre_ids: [18, 27],
        id: 133805,
        media_type: "movie",
        original_language: "en",
        original_title: "Carrie",
        overview:
          "A reimagining of the classic horror tale about Carrie White, a shy girl outcast by her peers and sheltered by her deeply religious mother, who unleashes telekinetic terror on her small town after being pushed too far at her senior prom.",
        poster_path: "/kloXz9qwO23z9Kbt3z3MgnjF4xO.jpg",
        release_date: "2013-10-16",
        title: "Carrie",
        video: false,
        vote_average: 6,
        vote_count: 3967,
      },
    ],
    known_for_department: "Acting",
    name: "Chloë Grace Moretz",
    popularity: 100.288,
    profile_path: "/u08QwcFnJpMtsDEYSlbUkMuE7bP.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 976,
    known_for: [
      {
        adult: false,
        backdrop_path: "/ysKahAEPP8h6MInuLjr0xuZOTjh.jpg",
        genre_ids: [80, 35],
        id: 107,
        media_type: "movie",
        original_language: "en",
        original_title: "Snatch",
        overview:
          "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
        poster_path: "/56mOJth6DJ6JhgoE2jtpilVqJO.jpg",
        release_date: "2000-09-01",
        title: "Snatch",
        video: false,
        vote_average: 7.8,
        vote_count: 7704,
      },
      {
        adult: false,
        backdrop_path: "/ibKeXahq4JD63z6uWQphqoJLvNw.jpg",
        genre_ids: [28, 878, 27],
        id: 345940,
        media_type: "movie",
        original_language: "en",
        original_title: "The Meg",
        overview:
          "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
        poster_path: "/xqECHNvzbDL5I3iiOVUkVPJMSbc.jpg",
        release_date: "2018-08-09",
        title: "The Meg",
        video: false,
        vote_average: 6.2,
        vote_count: 6152,
      },
      {
        adult: false,
        backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
        genre_ids: [28, 80, 53],
        id: 337339,
        media_type: "movie",
        original_language: "en",
        original_title: "The Fate of the Furious",
        overview:
          "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
        poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
        release_date: "2017-04-12",
        title: "The Fate of the Furious",
        video: false,
        vote_average: 6.9,
        vote_count: 9173,
      },
    ],
    known_for_department: "Acting",
    name: "Jason Statham",
    popularity: 98.015,
    profile_path: "/lldeQ91GwIVff43JBrpdbAAeYWj.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 453,
    known_for: [
      {
        adult: false,
        backdrop_path: "/oGMomeS7bE43eN8SGJUaKvQnmud.jpg",
        genre_ids: [18],
        id: 70,
        media_type: "movie",
        original_language: "en",
        original_title: "Million Dollar Baby",
        overview:
          "Despondent over a painful estrangement from his daughter, trainer Frankie Dunn isn't prepared for boxer Maggie Fitzgerald to enter his life. But Maggie's determined to go pro and to convince Dunn and his cohort to help her.",
        poster_path: "/mVqE0CaURUkiIXzHPOLVbTjAXFy.jpg",
        release_date: "2004-12-15",
        title: "Million Dollar Baby",
        video: false,
        vote_average: 8,
        vote_count: 8311,
      },
      {
        adult: false,
        backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
        genre_ids: [35, 80, 9648],
        id: 546554,
        media_type: "movie",
        original_language: "en",
        original_title: "Knives Out",
        overview:
          "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
        poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
        release_date: "2019-11-27",
        title: "Knives Out",
        video: false,
        vote_average: 7.9,
        vote_count: 9617,
      },
    ],
    known_for_department: "Acting",
    name: "Riki Lindhome",
    popularity: 97.301,
    profile_path: "/kJAGFp0ZW5sY0NoysFZcfSRykZa.jpg",
  },
];

export default people;
