const trending = [
  {
    adult: false,
    backdrop_path: "/2JeIqOdSM5nC1SQmuhUOfj3iB1U.jpg",
    id: 555604,
    title: "Guillermo del Toro's Pinocchio",
    original_language: "en",
    original_title: "Guillermo del Toro's Pinocchio",
    overview:
      "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
    poster_path: "/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
    media_type: "movie",
    genre_ids: [16, 14, 18],
    popularity: 222.841,
    release_date: "2022-11-09",
    video: false,
    vote_average: 8.391,
    vote_count: 183,
  },
  {
    adult: false,
    backdrop_path: "/ypFD4TJ3nLJesou76V59CnweaT0.jpg",
    id: 715931,
    title: "Emancipation",
    original_language: "en",
    original_title: "Emancipation",
    overview:
      "Inspired by the gripping true story of a man who would do anything for his family—and for freedom. When Peter, an enslaved man, risks his life to escape and return to his family, he embarks on a perilous journey of love and endurance.",
    poster_path: "/s9sUK1vAaOcxJfKzNTszrNkPhkH.jpg",
    media_type: "movie",
    genre_ids: [36, 18, 9648, 53, 28],
    popularity: 82.506,
    release_date: "2022-12-02",
    video: false,
    vote_average: 7.572,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/qF2i6oLZqpQKpwdLnTZf2eYXITN.jpg",
    id: 751741,
    title: "Night at the Museum: Kahmunrah Rises Again",
    original_language: "en",
    original_title: "Night at the Museum: Kahmunrah Rises Again",
    overview:
      "Nick Daley is following in his father's footsteps as night watchman at the American Museum of Natural History, so he knows what happens when the sun goes down. But when the maniacal ruler Kahmunrah escapes, it is up to Nick to save the museum once and for all.",
    poster_path: "/mkRQn520JQD07BNP03NK3iKCaPD.jpg",
    media_type: "movie",
    genre_ids: [16, 35, 10751, 14],
    popularity: 117.963,
    release_date: "2022-12-09",
    video: false,
    vote_average: 7.229,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/sNLP0dLZcVBqYa3MchCXJqgDtFb.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 7390.878,
    first_air_date: "2022-11-23",
    vote_average: 8.781,
    vote_count: 2545,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lcTuggU70y6pt6x13Rv1Ffjs93K.jpg",
    id: 112836,
    name: "Money Heist: Korea - Joint Economic Area",
    original_language: "ko",
    original_name: "종이의 집: 공동경제구역",
    overview:
      "Disguised under the shadows of a mask, a crew of desperados band together under the leadership of a criminal mastermind known only as “The Professor” to pull off the biggest heist Korea has ever seen.",
    poster_path: "/fjAAxDPzllwnCMqHDXYlw4IlkaL.jpg",
    media_type: "tv",
    genre_ids: [10759, 80, 18, 9648],
    popularity: 347.521,
    first_air_date: "2022-06-24",
    vote_average: 7.874,
    vote_count: 424,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/c5iPQhmZaq8eC8duhPTN373duEr.jpg",
    id: 890980,
    title: "God's Crooked Lines",
    original_language: "es",
    original_title: "Los renglones torcidos de Dios",
    overview:
      "Alice Gould, a private investigator, pretends to be mentally ill in order to enter a psychiatric hospital and gather evidence for the case she is working on: the death of a patient in unclear circumstances.",
    poster_path: "/hB2VqiLDiHAyLdZ1dlXIGqDJy06.jpg",
    media_type: "movie",
    genre_ids: [18, 9648, 53],
    popularity: 48.374,
    release_date: "2022-10-06",
    video: false,
    vote_average: 7.5,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/198vrF8k7mfQ4FjDJsBmdQcaiyq.jpg",
    id: 76600,
    title: "Avatar: The Way of Water",
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    media_type: "movie",
    genre_ids: [878, 28, 12],
    popularity: 998.982,
    release_date: "2022-12-14",
    video: false,
    vote_average: 8.682,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/wug15qrt09vllipUKXr6SNf74QT.jpg",
    id: 916053,
    title: "Something from Tiffany's",
    original_language: "en",
    original_title: "Something from Tiffany's",
    overview:
      "A woman’s life is upended when an engagement ring meant for someone else leads her to the person she’s meant to be with.",
    poster_path: "/hzQV66zQHqWKRjLVphISNOqadIp.jpg",
    media_type: "movie",
    genre_ids: [35, 10749],
    popularity: 33.076,
    release_date: "2022-11-29",
    video: false,
    vote_average: 6.4,
    vote_count: 28,
  },
  {
    adult: false,
    backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    id: 436270,
    title: "Black Adam",
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    media_type: "movie",
    genre_ids: [28, 14, 878],
    popularity: 5089.869,
    release_date: "2022-10-19",
    video: false,
    vote_average: 7.308,
    vote_count: 2656,
  },
  {
    adult: false,
    backdrop_path: "/jvvpsfpFdHwUvX1livlZ7R6HxhC.jpg",
    id: 961707,
    title: "Hawa",
    original_language: "fr",
    original_title: "Hawa",
    overview:
      "A teenage girl lives with her grandmother and worries she will be removed by social services. She sets off to get adopted by someone she admires more than anything, one of the most powerful women in the world.",
    poster_path: "/p6DhbsX1EuSJMtuOGsENkIOx1tt.jpg",
    media_type: "movie",
    genre_ids: [18, 35],
    popularity: 6.016,
    release_date: "2022-09-13",
    video: false,
    vote_average: 6.9,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/p22t7PQh1KGlweIlykFqZxSaIBE.jpg",
    id: 97113,
    name: "The Three-Body Problem",
    original_language: "zh",
    original_name: "三体",
    overview:
      "A science-fiction drama adapted from the novel of the same name by the famous science fiction writer Liu Cixin. “Three-Body Problem” tells the story of nanomaterials scientist Wang Miao and criminal police Shi Qiang who jointly unveiled the mystery of the “Three-Body Problem” world of an extraterrestrial civilization..",
    poster_path: "/l5mNr7kXp3aSzmIp9nRBZ6JUmVI.jpg",
    media_type: "tv",
    genre_ids: [16, 18, 9648, 10768, 10765],
    popularity: 40.404,
    first_air_date: "2022-12-10",
    vote_average: 7.4,
    vote_count: 5,
    origin_country: ["CN"],
  },
  {
    adult: false,
    backdrop_path: "/53BC9F2tpZnsGno2cLhzvGprDYS.jpg",
    id: 736526,
    title: "Troll",
    original_language: "no",
    original_title: "Troll",
    overview:
      "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
    poster_path: "/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
    media_type: "movie",
    genre_ids: [14, 28, 12],
    popularity: 4232.311,
    release_date: "2022-12-01",
    video: false,
    vote_average: 6.809,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: "/evxXVJtomJJbAXcDxF6wsCJzVDe.jpg",
    id: 1019836,
    title: "Christmas Bloody Christmas",
    original_language: "en",
    original_title: "Christmas Bloody Christmas",
    overview:
      "It's Christmas Eve and Tori just wants to get drunk and party, but when a robotic Santa Clause at a nearby toy store goes haywire and begins a rampant killing spree through her small town, she's forced into a battle for survival.",
    poster_path: "/60Dy8eA5QyUHKHBmojXUtZxWdo8.jpg",
    media_type: "movie",
    genre_ids: [27],
    popularity: 18.599,
    release_date: "2022-10-05",
    video: false,
    vote_average: 5.462,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: "/qwHZROaQnZEXGS1wpTLwDGn0gGi.jpg",
    id: 203805,
    name: "Dragon Age: Absolution",
    original_language: "en",
    original_name: "Dragon Age: Absolution",
    overview:
      "With great power at stake, a group of rebel mages and thieves goes head-to-head against a sinister force possessing a dangerous artifact.",
    poster_path: "/uw5N97cCH78ZQyx4OSV4qNVzZJ.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 16],
    popularity: 81.75,
    first_air_date: "2022-12-09",
    vote_average: 7.5,
    vote_count: 10,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/79PcXPpbDWql74h8Y00mNwbYMbS.jpg",
    id: 664469,
    title: "Amsterdam",
    original_language: "en",
    original_title: "Amsterdam",
    overview:
      "In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.",
    poster_path: "/6sJcVzGCwrDCBMV0DU6eRzA2UxM.jpg",
    media_type: "movie",
    genre_ids: [80, 35, 36, 9648, 53],
    popularity: 173.784,
    release_date: "2022-09-27",
    video: false,
    vote_average: 6.145,
    vote_count: 440,
  },
  {
    adult: false,
    backdrop_path: "/5tb7RjF0OAAaiGDUXsuedvhoGqV.jpg",
    id: 837881,
    title: "She Said",
    original_language: "en",
    original_title: "She Said",
    overview:
      "New York Times reporters Megan Twohey and Jodi Kantor break one of the most important stories in a generation — a story that helped launch the #MeToo movement and shattered decades of silence around the subject of sexual assault in Hollywood.",
    poster_path: "/jG4UI2dbNWlWtTTupjeU3fRJ5Fn.jpg",
    media_type: "movie",
    genre_ids: [18, 36],
    popularity: 139.919,
    release_date: "2022-11-17",
    video: false,
    vote_average: 7.341,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/o4HGJo4DmA0MugH4YozcMZofnZ9.jpg",
    id: 135157,
    name: "Alchemy of Souls",
    original_language: "ko",
    original_name: "환혼",
    overview:
      "A powerful sorceress in a blind woman's body encounters a man from a prestigious family, who wants her help to change his destiny.",
    poster_path: "/gvOZN1NlAoL8iz9ghpES1zWA3w3.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 9648, 10765],
    popularity: 156.6,
    first_air_date: "2022-06-18",
    vote_average: 8.7,
    vote_count: 196,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/olPXihyFeeNvnaD6IOBltgIV1FU.jpg",
    id: 882598,
    title: "Smile",
    original_language: "en",
    original_title: "Smile",
    overview:
      "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
    poster_path: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    media_type: "movie",
    genre_ids: [27, 9648, 53],
    popularity: 1071.457,
    release_date: "2022-09-23",
    video: false,
    vote_average: 6.829,
    vote_count: 1104,
  },
  {
    adult: false,
    backdrop_path: "/2T92w8l2iTnyG9jwOmIWfM9thRV.jpg",
    id: 1045944,
    title: "The Boss Baby: Christmas Bonus",
    original_language: "en",
    original_title: "The Boss Baby: Christmas Bonus",
    overview:
      "Christmas Eve takes a twisty turn when the Boss Baby accidentally swaps places with one of Santa's elves and gets stranded at the North Pole.",
    poster_path: "/iMmMxF6f2OonUrXrHKBLSYAhXly.jpg",
    media_type: "movie",
    genre_ids: [16, 10751, 12],
    popularity: 263.477,
    release_date: "2022-12-06",
    video: false,
    vote_average: 6.45,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/rfnmMYuZ6EKOBvQLp2wqP21v7sI.jpg",
    id: 774752,
    title: "The Guardians of the Galaxy Holiday Special",
    original_language: "en",
    original_title: "The Guardians of the Galaxy Holiday Special",
    overview:
      "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
    poster_path: "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    media_type: "movie",
    genre_ids: [35, 878, 12],
    popularity: 955.212,
    release_date: "2022-11-25",
    video: false,
    vote_average: 7.484,
    vote_count: 698,
  },
];

export default trending;
