export const trending = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/2JeIqOdSM5nC1SQmuhUOfj3iB1U.jpg",
      id: 555604,
      title: "Guillermo del Toro's Pinocchio",
      original_language: "en",
      original_title: "Guillermo del Toro's Pinocchio",
      overview:
        "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
      poster_path: "/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
      media_type: "movie",
      genre_ids: [16, 14, 18],
      popularity: 222.841,
      release_date: "2022-11-09",
      video: false,
      vote_average: 8.391,
      vote_count: 183,
    },
    {
      adult: false,
      backdrop_path: "/ypFD4TJ3nLJesou76V59CnweaT0.jpg",
      id: 715931,
      title: "Emancipation",
      original_language: "en",
      original_title: "Emancipation",
      overview:
        "Inspired by the gripping true story of a man who would do anything for his family—and for freedom. When Peter, an enslaved man, risks his life to escape and return to his family, he embarks on a perilous journey of love and endurance.",
      poster_path: "/s9sUK1vAaOcxJfKzNTszrNkPhkH.jpg",
      media_type: "movie",
      genre_ids: [36, 18, 9648, 53, 28],
      popularity: 82.506,
      release_date: "2022-12-02",
      video: false,
      vote_average: 7.572,
      vote_count: 69,
    },
  ],
  total_pages: 20,
  total_results: 200,
};
